# Generated by Django 4.0.1 on 2022-02-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
