# Generated by Django 4.0.1 on 2022-02-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_rename_products_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Qua', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
            ],
        ),
    ]
